apiVersion: apps/v1
kind: Deployment
metadata:
  name: bored-agent
  labels:
    app: bored-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bored-agent
  template:
    metadata:
      labels:
        app: bored-agent
    spec:
      serviceAccountName: bored-agent
      containers:
      - name: agent
        image: bored-agent:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BORED_TOKEN
          value: double0seven
        - name: IDP_PUBLIC_KEY
          value: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
            vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
            aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
            tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
            e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
            V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
            MwIDAQAB
            -----END PUBLIC KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: bored-agent-cert
  labels:
    app: bored-agent
data:
  public: ""
  private: ""
